name: skygate/expandable
typeName: skygate_expandable
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true

  -
    identifier: title
    type: Text
    required: true
    min: 4
    max: 15

  -
    identifier: textarea
    type: Textarea
    default: "Default value"
    placeholder: "Placeholder text"
    required: true
    rows: 15
    enableRichtext: true
    #richtextConfiguration: full

  -
    identifier: image
    type: File
    extendedPalette: true
    minitems: 1
    maxitems: 5
    allowed: common-image-types
    cropVariants:
      desktop:
        title: Desktop
        allowedAspectRatios:
          portrait:
            title: Portrait
            value: 0.75
          landscape:
            title: Landscape
            value: 4 / 3
        focusArea:
          x: 0.3
          y: 0.3
          width: 0.4
          height: 0.4
        coverAreas:
          - x: 0.1
            y: 0.8
            width: 0.8
            height: 0.1
      tablet:
        title: Tablet
        allowedAspectRatios:
          square:
            title: Square
            value: 0.75
      smartphone:
        title: Smartphone
        allowedAspectRatios:
          landscape:
            title: Landscape
            value: 4 / 3

