base: 'https://api.pwa-demo.ddev.site'
baseVariants:
  -
    base: 'https://api.t3pwa.com'
    condition: 'applicationContext == "Production/Production"'
    frontendBase: 'https://demo.t3pwa.com'
    frontendApiProxy: 'https://demo.t3pwa.com/headless'
    frontendFileApi: 'https://demo.t3pwa.com/headless/fileadmin'
dependencies:
  - skygate/sitepackage
  - friendsoftypo3/headless
  - nb-headless-content-blocks/headless-content-blocks
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=47'
frontendApiProxy: 'https://pwa-demo.ddev.site/headless'
frontendBase: 'https://pwa-demo.ddev.site'
frontendFileApi: 'https://pwa-demo.ddev.site/headless/fileadmin'
headless: 1
languages:
  -
    languageId: 0
    title: English
    navigationTitle: English
    base: /
    locale: en_US.UTF8
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    typo3Language: default
    flag: us
    enabled: true
  -
    languageId: 1
    title: Polish
    navigationTitle: Polish
    base: /pl/
    locale: pl_PL.UTF-8
    iso-639-1: pl
    hreflang: pl-PL
    direction: ltr
    typo3Language: default
    flag: pl
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
  -
    languageId: 2
    title: German
    navigationTitle: Deutsch
    base: /de/
    locale: de_DE.UTF8
    iso-639-1: de
    hreflang: de-DE
    direction: ltr
    typo3Language: de
    flag: de
    fallbackType: fallback
    fallbacks: '0'
    enabled: true
rootPageId: 43
# routeEnhancers:
#   ApiRoutes:
#     type: Extbase
#     limitToPages: [43]
#     extension: Sitepackage
#     plugin: User
#     routes:
#       - routePath: '/api/user'
#         _controller: 'UserApi::get'
#         _arguments: {}
#   CommentRoutes:
#     type: Extbase
#     limitToPages: [43]
#     extension: Sitepackage
#     plugin: CommentForm
#     routes:
#       - routePath: '/create-comment'
#         _controller: 'Comment::add'
#         _arguments: {}
websiteTitle: 'TYPO3 Headless & PWA Demo'
