#!/usr/bin/env bash

## Description: PWA Front ddev host commands for frontend setup
## Usage: setup-pwa-front
## Example: "ddev setup-pwa-front first-time"

YELLOW='\033[1;33m'
NC='\033[0m'

bold=$(tput bold)
normal=$(tput sgr0)

echo -e "${bold}Frontend has been rebuilt.\n\nUse ${YELLOW}ddev pwa-front start ${NC}${bold}to start frontend service and get server output in this console."
